# uncompyle6 version 3.8.0
# Python bytecode 2.7 (62211)
# Decompiled from: Python 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)]
# Embedded file name: scripts/client/gui/Scaleform/genConsts/PERSONAL_MISSIONS_BUTTONS.py


class PERSONAL_MISSIONS_BUTTONS(object):
    NO_BUTTONS = 0
    START_BTN_VISIBLE = 1
    START_BTN_ENABLED = 2
    RETRY_BTN_VISIBLE = 4
    DISCARD_BTN_VISIBLE = 8
    DISCARD_BTN_ENABLED = 16
    HOLD_AWARD_SHEET_BTN_VISIBLE = 32
    HOLD_AWARD_SHEET_BTN_ENABLED = 64
    OBTAIN_AWARD_BTN_VISIBLE = 128
    RETRY_BTN_ENABLED = 256
    PAUSE_BTN_VISIBLE = 512
    DETAILED_VIEW_BTN_STATES = [NO_BUTTONS, START_BTN_VISIBLE, START_BTN_ENABLED, RETRY_BTN_VISIBLE, DISCARD_BTN_VISIBLE, DISCARD_BTN_ENABLED, HOLD_AWARD_SHEET_BTN_VISIBLE, HOLD_AWARD_SHEET_BTN_ENABLED, OBTAIN_AWARD_BTN_VISIBLE, RETRY_BTN_ENABLED, PAUSE_BTN_VISIBLE]