# uncompyle6 version 3.9.0
# Python bytecode version base 2.7 (62211)
# Decompiled from: Python 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
# Embedded file name: scripts/client/gui/server_events/personal_progress/__init__.py
from personal_missions_constants import CONDITION_ICON
ORDERED_ICON_IDS = (
 CONDITION_ICON.FOLDER,
 CONDITION_ICON.IMPROVE,
 CONDITION_ICON.AWARD,
 CONDITION_ICON.MASTER,
 CONDITION_ICON.TOP,
 CONDITION_ICON.HURT_VEHICLES,
 CONDITION_ICON.KILL_VEHICLES,
 CONDITION_ICON.HIT,
 CONDITION_ICON.RAM,
 CONDITION_ICON.ASSIST_RADIO,
 CONDITION_ICON.MODULE_CRIT,
 CONDITION_ICON.FIRE,
 CONDITION_ICON.BASE_CAPTURE,
 CONDITION_ICON.BASE_DEF,
 CONDITION_ICON.DAMAGE_BLOCK,
 CONDITION_ICON.DAMAGE,
 CONDITION_ICON.DISCOVER,
 CONDITION_ICON.ASSIST_STUN_DURATION,
 CONDITION_ICON.ASSIST_STUN,
 CONDITION_ICON.ASSIST_STUN_MULTY,
 CONDITION_ICON.ASSIST_TRACK,
 CONDITION_ICON.ASSIST,
 CONDITION_ICON.PREPARATION,
 CONDITION_ICON.WIN,
 CONDITION_ICON.SURVIVE)